services:
  tuwunel:
    image: ghcr.io/matrix-construct/tuwunel:v1.9.3
    container_name: tuwunel

    restart: "no"
    stop_grace_period: 30m

    ports:
      - "8008:8008"

    environment:
      TUWUNEL_SERVER_NAME: ${TUWUNEL_SERVER_NAME:-my.matrix.host}
      TUWUNEL_ALLOW_REGISTRATION: "false"
      TUWUNEL_ALLOW_FEDERATION: "false"
      TUWUNEL_REGISTRATION_SHARED_SECRET: ${REGISTRATION_SHARED_SECRET}
      TUWUNEL_APPSERVICE_DIR: /etc/tuwunel/appservices

    volumes:
      - tuwunel-data:/var/lib/tuwunel
      - ./files/appservices:/etc/tuwunel/appservices:ro

volumes:
  tuwunel-data: